spring.application.name=PhotoAppWebClient
server.port= 8087

spring.security.oauth2.client.registration.photo-app-web-client.client-id = photo-app-web-client
spring.security.oauth2.client.registration.photo-app-web-client.client-secret = ohHPk7lSxpmwVcMFCIAPbZoNs5GkWOkI
spring.security.oauth2.client.registration.photo-app-web-client.scope = openid, profile, roles
spring.security.oauth2.client.registration.photo-app-web-client.authorization-grant-type = authorization_code



spring.security.oauth2.client.provider.photo-app-web-client.authorization-uri = http://localhost:8080/realms/photo-app-web-client/protocol/openid-connect/auth
spring.security.oauth2.client.provider.photo-app-web-client.token-uri = http://localhost:8080/realms/photo-app-web-client/protocol/openid-connect/token
spring.security.oauth2.client.provider.photo-app-web-client.jwk-set-uri=http://localhost:8080/realms/photo-app-web-client/protocol/openid-connect/certs
spring.security.oauth2.client.provider.photo-app-web-client.user-info-uri = http://localhost:8080/realms/photo-app-web-client/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.photo-app-web-client.user-name-attribute = preferred_username